ui:
  name: ui
  namespace: default
  replicaCount: 1
  targetPort: 3000
  port: 80
  uiImage: timotheeren/ui
  uiTag: sha-5c423bec3618c14d693bcbaccc56808084d0aab4

api:
  name: api
  namespace: default
  replicaCount: 1
  targetPort: 5678
  port: 5678
  apiImage: timotheeren/api
  apiTag: sha-5d158714157df0ea34255b5d4a7b3aafa7bce466
