credentials:
  username: admin
  password: furnace

ui:
  name: ui
  namespace: default
  replicaCount: 1
  targetPort: 3000
  port: 80
  uiImage: timotheeren/ui
  uiTag: sha-2f9b814b0fb87ab8f8e917d9a964ddf16cf726f0
  apiHost: http://api-service:5678

api:
  name: api
  namespace: default
  replicaCount: 1
  targetPort: 5678
  port: 5678
  apiImage: timotheeren/api
  apiTag: sha-4d08a6e9752f6ed956858d3fe46cb34adf787ad8
  redisHost: redis-service:6379

server:
  name: server
  namespace: default
  replicaCount: 1
  targetPort: 5678
  port: 5678
  serverImage: timotheeren/server
  serverTag: sha-2f9b814b0fb87ab8f8e917d9a964ddf16cf726f0
  redisHost: redis-service:6379

operator:
  name: operator
  namespace: system
  replicaCount: 1
  operatorImage: timotheeren/operator
  operatorTag: sha-9ab443cf05b79ab23dc516ab31c1b615fb3298c5
