credentials:
  username: admin
  password: furnace

ui:
  name: ui
  namespace: default
  replicaCount: 1
  targetPort: 3000
  port: 80
  uiImage: timotheeren/ui
  uiTag: sha-edc814d5079ac4ec92b8e7fd657ef126410d386b
  apiHost: http://api-service:5678

api:
  name: api
  namespace: default
  replicaCount: 1
  targetPort: 5678
  port: 5678
  apiImage: timotheeren/api
  apiTag: sha-ef9c7e7e7c190ddced627f1b9043b6926ea09fc1
  redisHost: redis-service:6379

server:
  name: server
  namespace: default
  replicaCount: 1
  targetPort: 5678
  port: 5678
  serverImage: timotheeren/server
  serverTag: sha-b908e48214401e1e671a59c1f74fc193abdddd86
  redisHost: redis-service:6379

operator:
  name: operator
  namespace: system
  replicaCount: 1
  operatorImage: timotheeren/operator
  operatorTag: sha-9ab443cf05b79ab23dc516ab31c1b615fb3298c5
