apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.server.name }}-service"
spec:
  selector:
    app: {{ .Values.server.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.targetPort }}
