apiVersion: v1
kind: Secret
metadata:
  name: sftp-credentials
  namespace: servers
type: Opaque
stringData:
  username: {{ .Values.credentials.username }}
  password: {{ .Values.credentials.password }}
