apiVersion: furnace.com/v1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: server-sample
spec:
  initContainer: nginx:latest
  requestMemory: "1Gi"
  requestCPU: "100m"
  limitMemory: "2Gi"
  limitCPU: "300m"
  storage: "1Gi"
