apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ui.name }}
  namespace: {{ .Values.ui.namespace }}
  labels:
    app: {{ .Values.ui.name }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ui.name }}
    spec:
      containers:
        - name: "{{ .Values.ui.name }}-container"
          image: '{{ .Values.ui.uiImage }}:{{ .Values.ui.uiTag }}'
          env:
            - name: HOSTNAME
              value: "0.0.0.0" 
            - name: PORT
              value: "3000"
            - name: API_HOST
              value: {{ .Values.ui.apiHost | quote }}
