name: API

on:
  push:
    paths:
      - 'api/**'
  workflow_dispatch:
    

jobs:
  ci:
    uses: timotheeren/Furnace/.github/workflows/ci.yml@main
    with:
      username: timotheeren
      image: "api"
      path: "api"
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
  
  cd:
    needs: ci
    uses: timotheeren/Furnace/.github/workflows/cd.yml@main
    with:
      image: "api"
      tag: "sha-${{ github.sha }}"
    secrets:
      token: ${{ secrets.PAT }}
