name: CI

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      image:
        required: true
        type: string
      path:
        required: true
        type: string
    secrets:
      dockerhub-username:
        required: true
      dockerhub-token:
        required: true

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout folder
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          path: ${{ inputs.path }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@a60f0f62b5c12316066c8db464bfb2faafd7907b
        with:
          image: ${{ inputs.username }}/${{ inputs.image }}
          tags: |
            type=ref, event=branch
            type=sha, format=long, prefix=sha

      - name: Login to DockerHub
        uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
